### ISSUE TITLE
Plugin throws error

### ISSUE THREAD

**Issue by rgarnett1955** [joelsa/kicad-hide-references-plugin#4]
<img width="312" alt="Snag_b0b62f9" src="https://github.com/joelsa/kicad-hide-references-plugin/assets/5625142/f5e3182e-69e1-4ec5-aa9b-42ae40e8405f">

Hi,

The plugin throws an error see attachment:

Application: KiCad x64 on x64

Version: 7.99.0-2508-gcd884211ef, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 8.0.0
	FontConfig 2.14.2
	libcurl/8.2.1-DEV Schannel zlib/1.2.13

Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Aug 31 2023 13:25:02
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.82.0
	OCC: 7.7.1
	Curl: 8.2.1-DEV
	ngspice: 40
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

**Comment by joelsa** [comment]
Hi, thank you very much for reporting this!

I haven't gotten around to using KiCad 7.99 yet, but will look into it this week.

**Comment by joelsa** [comment]
Turned out to be working perfectly fine in 8.0, so this was only a 7.99 issue.
